[package]
name = "sota-client-responder"
version = "0.1.0"
authors = ["Shaun Taheri <shaun@advancedtelematic.com>"]

[dependencies]
log = "0.3.6"
serde = "0.9.0-rc3"
serde_derive = "0.9.0-rc3"
serde_json = "0.8.6"
unix_socket = "0.5.0"
